# Setup
title:               RadicalXChange Paris
tagline:             'Home to the RadicalXChange Paris chapter'
description:         ''
url:                 TODO
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Olivier Milla
  url:               https://twitter.com/oliviermilla
  email:             olivier.milla@hey.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.9.0
google_analytics_id: #UA-XXXX-Y
